title: Complete Analysis LIDAR La Paz
description: Documentación del código LIDAR La Paz
theme: just-the-docs

url: https://ludcano.github.io/callp-docs

aux_links:
  GitHub CALLP: http://github.com/LFAUMSA/LIDAR_PYTHON

callouts:
  highlight:
    color: yellow
  librerias:
    title: Librerias
    color: blue
  new:
    title: Nuevo
    color: green
  note:
    title: Nota
    color: purple
  warning:
    title: Advertencia
    color: red
  parametros:
    title: Parámetros
    color: grey-lt
